const GET_ALL_MOVIES_LOADING = "GET_ALL_MOVIES_LOADING";
const GET_ALL_MOVIES_SUCCESS = "GET_ALL_MOVIES_SUCCESS";
const GET_ALL_MOVIES_ERROR = "GET_ALL_MOVIES_ERROR";

export {
  GET_ALL_MOVIES_LOADING,
  GET_ALL_MOVIES_SUCCESS,
  GET_ALL_MOVIES_ERROR
};